openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
components:
  schemas:
    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
        zip_code:
          type: string
        country:
          type: string

    Customer:
      type: object
      properties:
        customer_id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'

    OrderItem:
      type: object
      properties:
        product_id:
          type: string
        name:
          type: string
        quantity:
          type: integer
        price:
          type: number
        discount:
          type: number

    Order:
      type: object
      properties:
        order_id:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        total_price:
          type: number
        status:
          type: string
        metadata:
          type: object
          additionalProperties:
            type: string
