package main

type Address struct {
	Line2   string `json:"line2"`
	City    string `json:"city"`
	Zipcode string `json:"zipcode"`
	Country string `json:"country"`
	Line1   string `json:"line1"`
}

type Project struct {
	Id           string   `json:"id"`
	Name         string   `json:"name"`
	Completed    bool     `json:"completed"`
	Technologies []string `json:"technologies"`
}

type Preferences struct {
	Notifications bool   `json:"notifications"`
	Newsletter    bool   `json:"newsletter"`
	Theme         string `json:"theme"`
}

type Metadata struct {
	LoginCount int      `json:"login_count"`
	LastLogin  string   `json:"last_login"`
	Roles      []string `json:"roles"`
}

type AutoGenerated struct {
	UserId      int         `json:"user_id"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	Active      bool        `json:"active"`
	Balance     float64     `json:"balance"`
	Tags        []string    `json:"tags"`
	Address     Address     `json:"address"`
	Projects    []Project   `json:"projects"`
	Age         int         `json:"age"`
	CreatedAt   string      `json:"created_at"`
	Preferences Preferences `json:"preferences"`
	Metadata    Metadata    `json:"metadata"`
}
