package main

type Address struct {
	Line1 string `json:"line1"`
	Line2 string `json:"line2"`
	City string `json:"city"`
	Zipcode string `json:"zipcode"`
	Country string `json:"country"`
}

type Project struct {
	Completed bool `json:"completed"`
	Technologies []string `json:"technologies"`
	Id string `json:"id"`
	Name string `json:"name"`
}

type Preferences struct {
	Notifications bool `json:"notifications"`
	Newsletter bool `json:"newsletter"`
	Theme string `json:"theme"`
}

type Metadata struct {
	LoginCount int `json:"login_count"`
	LastLogin string `json:"last_login"`
	Roles []string `json:"roles"`
}

type AutoGenerated struct {
	Age int `json:"age"`
	Balance float64 `json:"balance"`
	CreatedAt string `json:"created_at"`
	Address Address `json:"address"`
	Projects []Project `json:"projects"`
	UserId int `json:"user_id"`
	Username string `json:"username"`
	Email string `json:"email"`
	Active bool `json:"active"`
	Tags []string `json:"tags"`
	Preferences Preferences `json:"preferences"`
	Metadata Metadata `json:"metadata"`
}

